version: "3.0"

services:
  entail-api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "9000:8080"
    command: "/app"
    environment:
      HTTP_PORT: 8080
    depends_on:
      - postgres
      - migrate
    networks:
      - entail

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: entail
      POSTGRES_PASSWORD: entail
      POSTGRES_DB: entail
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - entail

  migrate:
    image: migrate/migrate:v4.14.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - entail
    command: ["-path", "/migrations", "-database", "postgres://entail:entail@postgres:5432/entail?sslmode=disable", "up"]

networks:
    entail:
        driver: bridge