// Code generated by mockery. DO NOT EDIT.

package mockBalance

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBalance is an autogenerated mock type for the Balance type
type MockBalance struct {
	mock.Mock
}

type MockBalance_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalance) EXPECT() *MockBalance_Expecter {
	return &MockBalance_Expecter{mock: &_m.Mock}
}

// GetUserBalance provides a mock function with given fields: ctx, userID
func (_m *MockBalance) GetUserBalance(ctx context.Context, userID uint64) (float64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (float64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) float64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalance_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockBalance_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockBalance_Expecter) GetUserBalance(ctx interface{}, userID interface{}) *MockBalance_GetUserBalance_Call {
	return &MockBalance_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userID)}
}

func (_c *MockBalance_GetUserBalance_Call) Run(run func(ctx context.Context, userID uint64)) *MockBalance_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockBalance_GetUserBalance_Call) Return(_a0 float64, _a1 error) *MockBalance_GetUserBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalance_GetUserBalance_Call) RunAndReturn(run func(context.Context, uint64) (float64, error)) *MockBalance_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBalance creates a new instance of MockBalance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalance(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalance {
	mock := &MockBalance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
