// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Weeping-Willow/entain-task/internal/api"
	"github.com/Weeping-Willow/entain-task/internal/config"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	server := api.New(configConfig)
	app := NewApp(server)
	return app, func() {
	}, nil
}
