// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Weeping-Willow/entain-task/internal/api"
	"github.com/Weeping-Willow/entain-task/internal/config"
	"github.com/Weeping-Willow/entain-task/internal/repository"
	"github.com/Weeping-Willow/entain-task/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := config.NewDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userStorage := repository.NewUserStorage(db)
	balance := service.NewBalance(userStorage)
	server := api.New(configConfig, balance)
	app := NewApp(server)
	return app, func() {
		cleanup()
	}, nil
}
